#!/usr/bin/env bash

export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

location=$(man --location "$@")

if file --mime-type "$location" | grep -q 'gzip$'; then
    file=$(cat "$location" | gunzip)
else
    file=$(cat "$location")
fi

trying=$(printf "$file" | awk '/\.TH/ {gsub(/"/,"",$2);gsub(/"/,"",$3);print $2"("$3")";exit;}')

cat <(printf "$file" | groff -man -Tascii) /usr/share/clippy/clippy.png | \
    less -FirSX --prompt="It looks like you're trying to $trying. "
