#!/usr/bin/env bash

usage() {
    cat << HELP

  USAGE: $(basename $0) [-h|--help]

  --help|-h         Show this message

  It looks like you're trying to use clippy. You should be aware that,
  while this program can be used in lieu of man(1), it likely
  shouldn't be.
HELP
}

die() {
    local code="$1"
    shift
    printf "%b\n" "$@"
    cat /usr/share/clippy/clippy.png
    exit $code
}

show_man() {
    local file="$1"
    export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
    export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
    export LESS_TERMCAP_me=$'\E[0m'           # end mode
    export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
    export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
    export LESS_TERMCAP_ue=$'\E[0m'           # end underline
    export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

    trying=$(printf "$file" | awk '/\.TH/ {gsub(/"/,"",$2);gsub(/"/,"",$3);print $2"("$3")";exit;}')

    cat <(printf "$file" | groff -man -Tascii) /usr/share/clippy/clippy.png | \
        less -FirSX --prompt="It looks like you're trying to $trying. "
}

main() {
    if (( $# < 1 )) || [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; then
        usage
        die 0
    fi

    local location=$(man --location "$@")

    if [[ ! -f "$location" ]]; then
        die 1 "Man page not found for $@"
    fi

    if file --mime-type "$location" | grep -q 'gzip$'; then
        file=$(cat "$location" | gunzip)
    else
        file=$(cat "$location")
    fi

    show_man "$file"
}

main "$@"
